// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProyectoSegundo.Models;

namespace ProyectoSegundo.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20190723204303_proyFinalDB")]
    partial class proyFinalDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("ProyectoSegundo.Models.Abono", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CarteraId");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("Valor");

                    b.HasKey("id");

                    b.ToTable("Abonos");
                });

            modelBuilder.Entity("ProyectoSegundo.Models.Cartera", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConductorId");

                    b.Property<float>("DeudaActual");

                    b.Property<float>("DeudaInicial");

                    b.Property<string>("Estado");

                    b.Property<DateTime>("FechaUltimoPago");

                    b.Property<string>("Identificacion_Cond");

                    b.Property<int>("MesesPagados");

                    b.Property<int>("VehiculoId");

                    b.HasKey("id");

                    b.ToTable("Carteras");
                });

            modelBuilder.Entity("ProyectoSegundo.Models.Conductor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Asignado");

                    b.Property<string>("Identificacion");

                    b.Property<string>("NombreCompleto");

                    b.Property<string>("NumLicencia");

                    b.Property<string>("PrimerApellido");

                    b.Property<string>("PrimerNombre");

                    b.Property<string>("SegundoApellido");

                    b.Property<string>("SegundoNombre");

                    b.Property<string>("Telefono");

                    b.HasKey("id");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("ProyectoSegundo.Models.Propietario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Identificacion");

                    b.Property<string>("NombreCompleto");

                    b.Property<string>("PrimerApellido");

                    b.Property<string>("PrimerNombre");

                    b.Property<string>("SegundoApellido");

                    b.Property<string>("SegundoNombre");

                    b.Property<string>("Telefono");

                    b.HasKey("id");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("ProyectoSegundo.Models.Vehiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConductorId");

                    b.Property<DateTime>("FechaAfiliacion");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<string>("Placa");

                    b.Property<int>("PropietarioId");

                    b.HasKey("id");

                    b.ToTable("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
